services:
  - type: web
    name: telegram-gaml-bot
    plan: free
    runtime: docker
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: RENDER
        value: "true"
    healthCheckPath: /health
