services:
  - type: web
    name: telegram-gaml-bot
    plan: free
    runtime: docker
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: RENDER
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"
      - key: USER_AGENT
        value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
    healthCheckPath: /health
