services:
  - type: web
    name: telegram-gaml-bot
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome"
      - key: NODE_ENV
        value: "production"
      - key: RENDER
        value: "true"
    healthCheckPath: /health