services:
  - type: web
    name: telegram-gaml-bot
    plan: free
    runtime: node
    buildCommand: |
      apt-get update && 
      apt-get install -y wget gnupg && 
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg && 
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && 
      apt-get update && 
      apt-get install -y google-chrome-stable && 
      npm install
    startCommand: node bot.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome"
      - key: NODE_ENV
        value: "production"
      - key: RENDER
        value: "true"
    healthCheckPath: /health